services:
  apollo-api:
    image: apollo-api
    build:
      context: .
      dockerfile: src/Apollo.API/Dockerfile
    ports:
      - 5144:5144
    env_file:
      - .env
    depends_on:
      - pgsql
      - redis
    networks:
      - apollo

  apollo-discord:
    image: apollo-discord
    build:
      context: .
      dockerfile: src/Apollo.Discord/Dockerfile
    ports:
      - 5145:5145
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - apollo

  pgsql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-apollo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-apollo}
      - POSTGRES_DB=${POSTGRES_DB:-apollo_db}
    volumes:
      - pgsql_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - apollo

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-apollo_redis}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - apollo
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgsql_data:
  redis_data:

networks:
  apollo:
    driver: bridge
